### ISSUE TITLE
Add support of loading values from text file.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/wasserstoff#2]
It's easy:

File `text_file.txt`:
```ini
SMTP_SERVER=smtp.yandex.com
PORT=456
SSL=True
```
Using:
```python
>>> from wasserstoff import (
...     Config,
...     Environment,
... )
>>> env = Environment()
>>> dev = Config(
...     filename='text_file',
...     scope='dev',
... )
>>> env.patch(dev)
>>> env.commit()
```
Access to configurations:
```
>>> env.dev.SMTP_SERVER
'smtp.yandex.com'
```

**Comment by delta9000** [comment]
Hey, I just took a quick stab at this.  

Are you open to using a format parameter on the pull function?

I'm assuming a KEY=VALUE format split at the first instance of =

Test file:
```
key1=value1
key2=value2
key3=value3
base64=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=
badformat
SSL=true
```

Example:


```python
from wasserstoff import Config,Environment

env = Environment()

text = Config(filename='tests/data/text',scope='text',format='text')
```


```python
text.dictionary
```




    {'SSL': 'true',
     'base64': 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=',
     'key1': 'value1',
     'key2': 'value2',
     'key3': 'value3'}




```python
env.patch(text).commit()
```


```python
env.text.BASE64
```




    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='

**Comment by lk-geimfari** [comment]
@delta9000 Sure, `fmt` is useful. It should be `json` by default.
