### ISSUE TITLE
Add support of *.xml files

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/wasserstoff#3]
It would be awesome to support `xml` format, because it's in standard library.

**Comment by yo-ga** [comment]
Well...
Would you like to change the way to getting config like this?
```py
>>> dev = Config(
...     filename='dev.xml',
...     scope='dev',
... )
```

**Comment by kylec32** [comment]
Sorry. Forgot to say I was looking at this. I had the same question as above and ended up just preferring json (if there were both files available) and also allowing the specification of the extension.

**Comment by lk-geimfari** [comment]
@yo-ga Yes, but without extension of file:

>>> dev = Config(
...     filename='dev.xml',
...     scope='dev',
...     fmt='xml'
... )

**Comment by lk-geimfari** [comment]
@kylec32 Look at the answer please.

**Comment by lk-geimfari** [comment]
So, using xml is too dirty as i see. I close this issue. We will only support json, ini and text.
