### ISSUE TITLE
Generate sphinx documentation.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/wasserstoff#6]
We need the documentation. I suggest using [Sphinx](http://www.sphinx-doc.org/en/stable/).

**Comment by py-crash** [comment]
I think I could help with this. Anything other than the information on the readme and the autodocs?

**Comment by lk-geimfari** [comment]
@py-crash No, I think that's enough. Thanks!

**Comment by py-crash** [comment]
@lk-geimfari I sent a pull request, sorry that it took me so long.

**Comment by lk-geimfari** [comment]
@py-crash It's okay! Thanks!
